# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'async_await_firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for async_await_firebase
pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
pod 'FirebaseAuth', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'

end
